osx_image: xcode8.2
language: objective-c

xcode_workspace: ios/KidsPrize.xcworkspace
xcode_scheme: KidsPrize

install:
  - mkdir -p ~/.nvm
  - export NVM_DIR="~/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh

  # Use node 6 because that is what runs on land-blocking tests
  - nvm install 6
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.21.3/yarn-0.21.3.js
  - export yarn="node $(pwd)/yarn-0.21.3.js"
  - $yarn install

script:
- chmod a+x ./scripts/*.sh
- ./scripts/travis_build.sh

branches:
  only:
  - master
  - /^[0-9.]+/

cache:
  yarn: true
  directories:
    - node_modules
