// flow-typed signature: 067c65d37b48ca92e3908e3c7be4d4aa
// flow-typed version: <<STUB>>/native-base_v^0.5.11/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'native-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'native-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'native-base/Components/Base/NativeBaseComponent' {
  declare module.exports: any;
}

declare module 'native-base/Components/Themes/dark' {
  declare module.exports: any;
}

declare module 'native-base/Components/Themes/light' {
  declare module.exports: any;
}

declare module 'native-base/Components/vendor/react-native-drawer/index' {
  declare module.exports: any;
}

declare module 'native-base/Components/vendor/react-native-drawer/tween/tween-functions/index' {
  declare module.exports: any;
}

declare module 'native-base/Components/vendor/react-native-drawer/tweener' {
  declare module.exports: any;
}

declare module 'native-base/Components/vendor/react-native-scrollable-tab-view/DefaultTabBar' {
  declare module.exports: any;
}

declare module 'native-base/Components/vendor/react-native-scrollable-tab-view/index' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Badge' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Button' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Card' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/CardItem' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/CardSwiper' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Checkbox' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Container' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Content' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/DeckSwiper' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Footer' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/FooterTab' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/H1' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/H2' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/H3' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Header' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Icon' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Input' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/InputGroup' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/List' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/ListItem' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Picker.ios' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Picker' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/ProgressBar.android' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/ProgressBar.ios' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Radio' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Spinner' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Subtitle' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Switch' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Tabs' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Text' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Textarea' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Thumbnail' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/Title' {
  declare module.exports: any;
}

declare module 'native-base/Components/Widgets/View' {
  declare module.exports: any;
}

declare module 'native-base/Utils/computeProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'native-base/Components/Base/NativeBaseComponent.js' {
  declare module.exports: $Exports<'native-base/Components/Base/NativeBaseComponent'>;
}
declare module 'native-base/Components/Themes/dark.js' {
  declare module.exports: $Exports<'native-base/Components/Themes/dark'>;
}
declare module 'native-base/Components/Themes/light.js' {
  declare module.exports: $Exports<'native-base/Components/Themes/light'>;
}
declare module 'native-base/Components/vendor/react-native-drawer/index.js' {
  declare module.exports: $Exports<'native-base/Components/vendor/react-native-drawer/index'>;
}
declare module 'native-base/Components/vendor/react-native-drawer/tween/tween-functions/index.js' {
  declare module.exports: $Exports<'native-base/Components/vendor/react-native-drawer/tween/tween-functions/index'>;
}
declare module 'native-base/Components/vendor/react-native-drawer/tweener.js' {
  declare module.exports: $Exports<'native-base/Components/vendor/react-native-drawer/tweener'>;
}
declare module 'native-base/Components/vendor/react-native-scrollable-tab-view/DefaultTabBar.js' {
  declare module.exports: $Exports<'native-base/Components/vendor/react-native-scrollable-tab-view/DefaultTabBar'>;
}
declare module 'native-base/Components/vendor/react-native-scrollable-tab-view/index.js' {
  declare module.exports: $Exports<'native-base/Components/vendor/react-native-scrollable-tab-view/index'>;
}
declare module 'native-base/Components/Widgets/Badge.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Badge'>;
}
declare module 'native-base/Components/Widgets/Button.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Button'>;
}
declare module 'native-base/Components/Widgets/Card.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Card'>;
}
declare module 'native-base/Components/Widgets/CardItem.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/CardItem'>;
}
declare module 'native-base/Components/Widgets/CardSwiper.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/CardSwiper'>;
}
declare module 'native-base/Components/Widgets/Checkbox.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Checkbox'>;
}
declare module 'native-base/Components/Widgets/Container.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Container'>;
}
declare module 'native-base/Components/Widgets/Content.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Content'>;
}
declare module 'native-base/Components/Widgets/DeckSwiper.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/DeckSwiper'>;
}
declare module 'native-base/Components/Widgets/Footer.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Footer'>;
}
declare module 'native-base/Components/Widgets/FooterTab.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/FooterTab'>;
}
declare module 'native-base/Components/Widgets/H1.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/H1'>;
}
declare module 'native-base/Components/Widgets/H2.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/H2'>;
}
declare module 'native-base/Components/Widgets/H3.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/H3'>;
}
declare module 'native-base/Components/Widgets/Header.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Header'>;
}
declare module 'native-base/Components/Widgets/Icon.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Icon'>;
}
declare module 'native-base/Components/Widgets/Input.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Input'>;
}
declare module 'native-base/Components/Widgets/InputGroup.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/InputGroup'>;
}
declare module 'native-base/Components/Widgets/List.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/List'>;
}
declare module 'native-base/Components/Widgets/ListItem.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/ListItem'>;
}
declare module 'native-base/Components/Widgets/Picker.ios.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Picker.ios'>;
}
declare module 'native-base/Components/Widgets/Picker.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Picker'>;
}
declare module 'native-base/Components/Widgets/ProgressBar.android.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/ProgressBar.android'>;
}
declare module 'native-base/Components/Widgets/ProgressBar.ios.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/ProgressBar.ios'>;
}
declare module 'native-base/Components/Widgets/Radio.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Radio'>;
}
declare module 'native-base/Components/Widgets/Spinner.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Spinner'>;
}
declare module 'native-base/Components/Widgets/Subtitle.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Subtitle'>;
}
declare module 'native-base/Components/Widgets/Switch.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Switch'>;
}
declare module 'native-base/Components/Widgets/Tabs.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Tabs'>;
}
declare module 'native-base/Components/Widgets/Text.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Text'>;
}
declare module 'native-base/Components/Widgets/Textarea.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Textarea'>;
}
declare module 'native-base/Components/Widgets/Thumbnail.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Thumbnail'>;
}
declare module 'native-base/Components/Widgets/Title.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/Title'>;
}
declare module 'native-base/Components/Widgets/View.js' {
  declare module.exports: $Exports<'native-base/Components/Widgets/View'>;
}
declare module 'native-base/index' {
  declare module.exports: $Exports<'native-base'>;
}
declare module 'native-base/index.js' {
  declare module.exports: $Exports<'native-base'>;
}
declare module 'native-base/Utils/computeProps.js' {
  declare module.exports: $Exports<'native-base/Utils/computeProps'>;
}
