// flow-typed signature: 5f0acee1780a9744b3b5d52a05cc6e54
// flow-typed version: <<STUB>>/react-native-device-info_v^0.9.7/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-device-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-device-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-device-info/deviceinfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-device-info/deviceinfo.js' {
  declare module.exports: $Exports<'react-native-device-info/deviceinfo'>;
}
