// flow-typed signature: e3fc5c711495a70a0b25ff8accde43f8
// flow-typed version: <<STUB>>/react-native-cookies_v^2.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-cookies/index' {
  declare module.exports: $Exports<'react-native-cookies'>;
}
declare module 'react-native-cookies/index.js' {
  declare module.exports: $Exports<'react-native-cookies'>;
}
