// flow-typed signature: 7f5b515916dff852736da6f405ca53b3
// flow-typed version: <<STUB>>/react-native-sortable-listview_v^0.1.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sortable-listview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sortable-listview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sortable-listview/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sortable-listview/example.js' {
  declare module.exports: $Exports<'react-native-sortable-listview/example'>;
}
declare module 'react-native-sortable-listview/index' {
  declare module.exports: $Exports<'react-native-sortable-listview'>;
}
declare module 'react-native-sortable-listview/index.js' {
  declare module.exports: $Exports<'react-native-sortable-listview'>;
}
