// flow-typed signature: c1a1c3c86276cbe25d74b332c9fd6a53
// flow-typed version: <<STUB>>/react-addons-update_v15.4.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-update/index' {
  declare module.exports: $Exports<'react-addons-update'>;
}
declare module 'react-addons-update/index.js' {
  declare module.exports: $Exports<'react-addons-update'>;
}
